services:
  - type: web
    name: url-shortener-backend
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: BASE_URL
        generateValue: true 